name: Package ZIPs

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create plugin and theme ZIPs
        run: |
          mkdir -p dist
          for dir in plugins/* themes/*; do
            if [ -d "$dir" ]; then
              name="$(basename "$dir")"
              zip -r "dist/${name}.zip" "$dir"
            fi
          done
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
